# Generated by Django 5.0.3 on 2024-07-02 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0002_alter_appointment_date_usersubcribes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 2, 20, 44, 31, 109747)),
        ),
    ]
